[tool.coverage.run]
branch = true
data_file = ".coverage/.coverage"

[tool.flake8]
ban-relative-imports = true
max-line-length = 88

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-vv"
filterwarnings = "error"
timeout = 1
