[build-system]
requires = ["setuptools >= 65.0.0,<65.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mvnb"
version = "0.0.0"
dependencies = [
  "bidict>=0.22.0,<0.23.0",
  "tornado>=6.2.0,<6.3.0",
]

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "flake8-black",
    "isort",
    "pytest-cov",
    "pytest-timeout",
]

[project.scripts]
mvnb-cui = "mvnb.cui.__main__:main"
mvnb-server = "mvnb.server.__main__:main"

[tool.setuptools]
packages = [
  "mvnb.cui",
  "mvnb.model",
  "mvnb.server",
  "mvnb.util",
]

[tool.setuptools.package-dir]
mvnb = "src"

[tool.coverage.run]
branch = true
data_file = ".coverage/.coverage"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.pytest.ini_options]
addopts = "-vv"
filterwarnings = "error"
timeout = 1
