[build-system]
requires = ["setuptools >= 65.0.0,<65.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mvnb"
version = "0.0.0"
dependencies = [
    "bidict >=0.22.0,<0.23.0",
    "tornado >=6.2.0,<6.3.0"
]

[project.scripts]
mvnb-server = "mvnb.server:main"
mvnb-console = "mvnb.console:main"

[tool.setuptools]
packages = ["mvnb"]
package-dir = {mvnb = "src"}

[tool.coverage.run]
branch = true
data_file = ".coverage/.coverage"

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.pytest.ini_options]
addopts = "-vv"
filterwarnings = "error"
timeout = 1
